zzyl:
  framework:
    security:
      ignore-url:
        #        - /**
        - /resource/menus/**
        - /resource/myButten/**
        - /customer/**
        - /security/login
        - /security/logout
        - /doc.html
        - /*-swagger/**
        - /swagger-resources
        - /v2/api-docs
        - /webjars/**
        - /common/**
        - /ws/**
      public-access-urls:
        - PUT/bill/cancel/**
        - POST/role/init-roles
        - GET/room/getRoomsCheckedByFloorId/**
        - GET/roomTypes/status/**
        - POST/orders/**
        - PUT/bed/update
        - GET/contract/list
        - DELETE/post/**
        - PUT/contract
        - PUT/nursing/**
        - PUT/nursingTask/do
        - PATCH/dept/is_enable
        - POST/bill
        - DELETE/nursing_project/**
        - GET/roomTypes
        - POST/user/list
        - PUT/nursing/plan/**
        - PUT/nursingTask/cancel
        - DELETE/nursingLevel/delete/**
        - GET/room/getRoomsWithNurByFloorId/**
        - GET/visit/page
        - GET/iot/allProduct
        - GET/elder/selectList
        - PUT/nursingLevel/update
        - GET/visit
        - GET/floor/getAllWithRoomAndBed
        - GET/nursingTask/page
        - GET/bill/page
        - GET/message/pageQuery
        - PUT/reservation/**
        - DELETE/floor/delete/**
        - GET/swagger-resources
        - PUT/checkIn/reject
        - PUT/nursing_project
        - POST/checkIn
        - POST/dept/tree
        - PATCH/dept
        - PUT/checkIn
        - GET/elder/selectByIdCard
        - GET/roomTypes/typeName/**
        - GET/room/get/**
        - PUT/nursingLevel/**
        - PUT/user
        - PUT/checkIn/revocation
        - POST/checkIn/review
        - DELETE/message/allDelete
        - GET/nursingTask
        - GET/roomTypes/**
        - GET/bill/balance
        - PUT/alert-rule/update/**
        - GET/room/getRoomsWithDeviceByFloorId/**
        - GET/orders
        - POST/iot/QueryDeviceDetail
        - POST/checkIn/create
        - PUT/dept
        - PATCH/user
        - GET/alert-rule/read/**
        - POST/applications/selectByPage
        - PATCH/role
        - GET/user/current-user
        - POST/common/upload
        - DELETE/visit/**
        - DELETE/nursing/plan/**
        - GET/bill/**
        - PUT/checkIn/cancel
        - GET/nursing/plan
        - GET/iot/pageQueryDevice
        - POST/floor/add
        - GET/bill/arrears
        - GET/retreat_bills
        - GET/nursingLevel/listByPage
        - POST/iot/deviceOpenDoor/**
        - GET/bill/prepaidRechargeRecord/page
        - GET/iot/queryDeviceListByProductKey/**
        - POST/post/list
        - GET/message/queryVoiceNotifyStatus
        - PUT/alert-data/handleAlertData/**
        - GET/reservation
        - GET/alert-rule/get-page
        - DELETE/contract/**
        - GET/bed/read/**
        - DELETE/reservation/**
        - POST/post/page/**
        - PUT/post
        - POST/dept/list
        - PUT/retreat_bills/uploadRefundVoucher
        - POST/visit
        - POST/iot/UpdateDevice
        - POST/nursing/plan
        - PUT/checkIn/submit
        - POST/alert-rule/create
        - POST/orders/refund
        - POST/security/login
        - GET/bed/read/room/**
        - PUT/nursingTask/updateTime
        - DELETE/message/batchDelete
        - GET/alert-data/pageQuery
        - DELETE/bed/delete/**
        - DELETE/alert-rule/delete/**
        - POST/iot/QueryDevicePropertyStatus
        - PUT/room/update
        - PUT/visit/**
        - POST/reservation
        - PUT/message/updateVoiceNotifyStatus/**
        - GET/elder/selectListByPage
        - PUT/roomTypes/**
        - PUT/message/batchMarkRead
        - GET/orders/search
        - POST/orders/**
        - DELETE/iot/DeleteDevice
        - GET/visit/**
        - POST/checkIn/sign
        - POST/iot/QueryThingModelPublished
        - PUT/roomTypes/**
        - GET/trade-common-feign/query-refund
        - PUT/elder/setNursing
        - GET/checkIn
        - GET/floor/getAllFloorsWithDevice
        - PUT/nursing_project/**
        - GET/nursing_project/all
        - POST/nursingLevel/insertBatch
        - PUT/alert-rule/**
        - GET/iot/pageQueryDeviceServiceData
        - GET/floor/get/**
        - GET/message/countByReadStatus
        - DELETE/user/remove/**
        - DELETE/roomTypes/**
        - GET/nursing_project/**
        - GET/contract/**
        - PUT/reservation/**
        - POST/bed/create
        - POST/nursing_project
        - GET/reservation/**
        - GET/room/getRoomsByFloorId/**
        - GET/room/getAllVo
        - GET/nursing/plan/search
        - GET/nursingLevel/listAll
        - PUT/visit/**
        - POST/bill/prepaidRechargeRecord
        - GET/nursingLevel/**
        - POST/nursingLevel/insert
        - POST/user/page/**
        - GET/endpoints
        - GET/c-user/page
        - POST/pending_tasks/selectByPage
        - DELETE/room/delete/**
        - PATCH/post
        - GET/device-data/get-page
        - POST/iot/RegisterDevice
        - PUT/message/allMarkRead
        - PUT/role
        - PUT/user/is-enable/**
        - GET/floor/getAllFloorsWithNur
        - POST/role/page/**
        - POST/trade-common-feign/query-refund-record
        - GET/nursing_project
        - POST/iot/syncProductList
        - PUT/floor/update
        - GET/reservation/countByTime
        - DELETE/dept/**
        - PUT/reservation/**
        - POST/user/reset-passwords/**
        - POST/bill/payRecord
        - POST/roomTypes
        - GET/reservation/page
        - GET/floor/getAll
        - POST/room/add
        - DELETE/role/**
        - GET/nursing/plan/**
        - GET/resource/menus
        - POST/resource/list
        - PATCH/resource
        - POST/resource/enable
        - POST/resource/tree
        - GET/resource/myButten
        - PUT/resource
        - DELETE/resource/**